// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM6JW0Qz1L9w0vE_3L5GjwaA1KZcPbGvA',
    appId: '1:199013239629:web:e6d59836297c24a8bec504',
    messagingSenderId: '199013239629',
    projectId: 'todo-app-ec271',
    authDomain: 'todo-app-ec271.firebaseapp.com',
    storageBucket: 'todo-app-ec271.appspot.com',
    measurementId: 'G-XD9VDTM1G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78SzoXYHpzPGC49H1iSeE1edF4xBeVnk',
    appId: '1:199013239629:android:7c4aa3bf8b0298d7bec504',
    messagingSenderId: '199013239629',
    projectId: 'todo-app-ec271',
    storageBucket: 'todo-app-ec271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuyanONgUIQ0t39muGf9WcYvEa0tFv9us',
    appId: '1:199013239629:ios:4b289fe4d1416aebbec504',
    messagingSenderId: '199013239629',
    projectId: 'todo-app-ec271',
    storageBucket: 'todo-app-ec271.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuyanONgUIQ0t39muGf9WcYvEa0tFv9us',
    appId: '1:199013239629:ios:e587d3589c13dfbebec504',
    messagingSenderId: '199013239629',
    projectId: 'todo-app-ec271',
    storageBucket: 'todo-app-ec271.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
